disabled_rules:
  - force_unwrapping
  - force_try                  
  - function_body_length       
  - line_length                
  - cyclomatic_complexity

identifier_name:
  max_length: 100     
